artifacts_root: artifact

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/saisuryachandraprasad/opensrc_data/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

